version: 2
jobs:
  build:
    docker:
       - image: thinkshout/nginx-php-fpm@sha256:e24a56b754eaac4e4292a1e162d2d20e69cac551def51c8da3b592b7f2787e4e
         environment:
           WEBROOT: /var/www/html/drupal-project/web
           GIT_EMAIL: "ci@thinkshout.com"
           GIT_NAME: "ThinkShout CI Bot"
         cmd: ["/start.sh"]
       - image: mariadb:10.0
         environment:
           MYSQL_RANDOM_ROOT_PASSWORD: 1
           MYSQL_DATABASE: drupal
           MYSQL_USER: drupal
           MYSQL_PASSWORD: drupal
      #  - image: thinkshout/docker-solr:3.6-pantheon
    working_directory: /var/www/html/drupal-project
    steps:
      - checkout
      - type: add-ssh-keys
      - run:
          name: Project configuration
          command: |
            export PATH="./vendor/bin:../vendor/bin:/root/.composer/vendor/bin:$PATH"
            composer global require -n "hirak/prestissimo:^0.3"
            composer global require -n "consolidation/cgr"
            cgr "pantheon-systems/terminus:~1"
            composer install --prefer-dist
            robo configure --db-name=drupal --db-user=drupal --db-pass=drupal --db-host=127.0.0.1
      - run:
          name: Install and test
          command: |
            export PATH="./vendor/bin:../vendor/bin:/root/.composer/vendor/bin:$PATH"
            robo install
            robo test --profile ci
