module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  block: 0
  block_content: 0
  breakpoint: 0
  chosen: 0
  chosen_lib: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  crop: 0
  ctools: 0
  ctools_views: 0
  datetime: 0
  dblog: 0
  ds: 0
  dynamic_page_cache: 0
  editor: 0
  editor_advanced_link: 0
  email_registration: 0
  embed: 0
  entity: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference: 0
  entity_reference_revisions: 0
  fast404: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  google_analytics: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  image_widget_crop: 0
  inline_entity_form: 0
  layout_plugin: 0
  link: 0
  linkit: 0
  media: 0
  media_entity: 0
  media_entity_document: 0
  media_entity_image: 0
  media_entity_instagram: 0
  media_entity_twitter: 0
  memcache: 0
  menu_ui: 0
  metatag: 0
  metatag_google_plus: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  migrate: 0
  migrate_google_sheets: 0
  migrate_plus: 0
  migrate_tools: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  pathauto: 0
  quickedit: 0
  r4032login: 0
  rdf: 0
  redirect: 0
  responsive_image: 0
  search: 0
  shortcut: 0
  simple_sitemap: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  video_embed_field: 0
  video_embed_media: 0
  views_ui: 0
  menu_link_content: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
